# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_User_Dialog(object):
    def __init__(self):
        self.Sys = None

    def setupUi(self, Add_User_Dialog, Sys, img):
        self.Sys = Sys

        def on_accept():
            """
            ok按钮事件函数
            :return:
            """
            try:
                # 执行其他操作
                frame = img
                user_name = self.input_username.text()
                # 添加用户人脸特征向量
                self.Sys.um.add_new_user_Client(frame, user_name, self.Sys.modelD_path, self.Sys.modelR_path,
                                                self.Sys.input_shape)
                self.Sys.faReSys.set_user_lists(self.Sys.um.list)
                # 添加用户rgb值到数据库
                # user_id = self.Sys.db.query_user_id(user_name)
                R = self.R_Content.text()
                G = self.G_Content.text()
                B = self.B_Content.text()
                self.Sys.db.insert(user_name, R, G, B)
                # 从数据库重新加载rgb信息
                query_all_user = self.Sys.db.query_all_user()
                self.Sys.um.load_rgbs(query_all_user)
                Add_User_Dialog.accept()
            except Exception as e:
                print("Error:", e)

        Add_User_Dialog.setObjectName("Add_User_Dialog")
        Add_User_Dialog.resize(640, 1020)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHeightForWidth(Add_User_Dialog.sizePolicy().hasHeightForWidth())
        Add_User_Dialog.setSizePolicy(sizePolicy)

        self.gridLayout = QtWidgets.QGridLayout(Add_User_Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        self.label_face_img = QtWidgets.QLabel(Add_User_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHeightForWidth(self.label_face_img.sizePolicy().hasHeightForWidth())
        self.label_face_img.setSizePolicy(sizePolicy)
        self.label_face_img.setObjectName("label_face_img")
        self.verticalLayout.addWidget(self.label_face_img)

        self._layout_username = QtWidgets.QHBoxLayout()
        self._layout_username.setObjectName("_layout_username")
        self.label_username = QtWidgets.QLabel(Add_User_Dialog)

        font = QtGui.QFont()
        font.setPointSize(12)

        self.label_username.setFont(font)
        self.label_username.setObjectName("label_username")
        self._layout_username.addWidget(self.label_username)

        self.input_username = QtWidgets.QLineEdit(Add_User_Dialog)
        self.input_username.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.input_username.setObjectName("input_username")
        self._layout_username.addWidget(self.input_username)
        self.verticalLayout.addLayout(self._layout_username)

        self._layout_personalized = QtWidgets.QHBoxLayout()
        self._layout_personalized.setObjectName("_layout_personalized")
        self.label_personalized = QtWidgets.QLabel(Add_User_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHeightForWidth(self.label_personalized.sizePolicy().hasHeightForWidth())
        self.label_personalized.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_personalized.setFont(font)
        self.label_personalized.setObjectName("label_personalized")
        self._layout_personalized.addWidget(self.label_personalized)

        self.label_personalized_rgb = QtWidgets.QLabel(Add_User_Dialog)
        self.label_personalized_rgb.setFont(font)
        self.label_personalized_rgb.setObjectName("label_personalized_rgb")
        self._layout_personalized.addWidget(self.label_personalized_rgb)
        self.verticalLayout.addLayout(self._layout_personalized)

        self.tabWidget = QtWidgets.QTabWidget(Add_User_Dialog)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 150))
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")

        self.rgb_cold_warm = QtWidgets.QWidget()
        self.rgb_cold_warm.setObjectName("rgb_cold_warm")
        self.widget = QtWidgets.QWidget(self.rgb_cold_warm)
        self.widget.setGeometry(QtCore.QRect(30, 20, 431, 31))
        self.widget.setObjectName("widget")

        self._layout_silder = QtWidgets.QHBoxLayout(self.widget)
        self._layout_silder.setContentsMargins(0, 0, 0, 0)
        self._layout_silder.setObjectName("_layout_silder")

        self.rgb_cold = QtWidgets.QLabel(self.widget)
        self.rgb_cold.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rgb_cold.setFont(font)
        self.rgb_cold.setObjectName("rgb_cold")
        self._layout_silder.addWidget(self.rgb_cold)

        self.rgbSlider = QtWidgets.QSlider(self.widget)
        self.rgbSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rgbSlider.setObjectName("rgbSlider")
        self._layout_silder.addWidget(self.rgbSlider)

        self.rgb_warm = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rgb_warm.sizePolicy().hasHeightForWidth())
        self.rgb_warm.setSizePolicy(sizePolicy)
        self.rgb_warm.setFont(font)
        self.rgb_warm.setObjectName("rgb_warm")
        self._layout_silder.addWidget(self.rgb_warm)

        self.rgb_show_cold_warm = QtWidgets.QLabel(self.rgb_cold_warm)
        self.rgb_show_cold_warm.setGeometry(QtCore.QRect(30, 70, 431, 41))
        self.rgb_show_cold_warm.setText("")
        self.rgb_show_cold_warm.setObjectName("rgb_show_cold_warm")
        self.tabWidget.addTab(self.rgb_cold_warm, "")

        self.rgb_customize = QtWidgets.QWidget()
        self.rgb_customize.setObjectName("rgb_customize")
        self.rgb_show_2 = QtWidgets.QLabel(self.rgb_customize)
        self.rgb_show_2.setGeometry(QtCore.QRect(40, 70, 401, 41))
        self.rgb_show_2.setText("")
        self.rgb_show_2.setObjectName("rgb_show_2")

        self.widget1 = QtWidgets.QWidget(self.rgb_customize)
        self.widget1.setGeometry(QtCore.QRect(40, 20, 401, 41))
        self.widget1.setObjectName("widget1")

        self.rgb_input = QtWidgets.QHBoxLayout(self.widget1)
        self.rgb_input.setContentsMargins(0, 0, 0, 0)
        self.rgb_input.setObjectName("rgb_input")

        self.R = QtWidgets.QLabel(self.widget1)
        self.R.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.R.setFont(font)
        self.R.setObjectName("R")
        self.rgb_input.addWidget(self.R)
        self.R_Content = QtWidgets.QLineEdit(self.widget1)
        self.R_Content.setMaximumSize(QtCore.QSize(80, 16777215))
        self.R_Content.setObjectName("R_Content")
        self.rgb_input.addWidget(self.R_Content)
        self.G = QtWidgets.QLabel(self.widget1)
        self.G.setMaximumSize(QtCore.QSize(20, 16777215))
        self.G.setFont(font)
        self.G.setObjectName("G")
        self.rgb_input.addWidget(self.G)
        self.G_Content = QtWidgets.QLineEdit(self.widget1)
        self.G_Content.setMaximumSize(QtCore.QSize(80, 16777215))
        self.G_Content.setObjectName("G_Content")
        self.rgb_input.addWidget(self.G_Content)
        self.B = QtWidgets.QLabel(self.widget1)
        self.B.setMaximumSize(QtCore.QSize(20, 16777215))
        self.B.setFont(font)
        self.B.setObjectName("B")
        self.rgb_input.addWidget(self.B)
        self.B_Content = QtWidgets.QLineEdit(self.widget1)
        self.B_Content.setMaximumSize(QtCore.QSize(80, 16777215))
        self.B_Content.setObjectName("B_Content")
        self.rgb_input.addWidget(self.B_Content)

        self.tabWidget.addTab(self.rgb_customize, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 2, 1)

        self.boundaryLine = QtWidgets.QFrame(Add_User_Dialog)
        self.boundaryLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.boundaryLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.boundaryLine.setObjectName("boundaryLine")
        self.gridLayout.addWidget(self.boundaryLine, 0, 1, 2, 1)

        self.buttonBox = QtWidgets.QDialogButtonBox(Add_User_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 2, 1, 1)

        self.retranslateUi(Add_User_Dialog)
        self.tabWidget.setCurrentIndex(1)
        self.buttonBox.accepted.connect(on_accept)
        self.buttonBox.rejected.connect(Add_User_Dialog.reject)

        QtCore.QMetaObject.connectSlotsByName(Add_User_Dialog)

    def retranslateUi(self, Add_User_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Add_User_Dialog.setWindowTitle(_translate("Add_User_Dialog", "添加用户"))
        self.label_username.setText(_translate("Add_User_Dialog", "用户姓名"))
        self.label_personalized.setText(_translate("Add_User_Dialog", "个性化：灯光色温"))
        self.rgb_cold.setText(_translate("Add_User_Dialog", "冷色"))
        self.rgb_warm.setText(_translate("Add_User_Dialog", "暖色"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rgb_cold_warm), _translate("Add_User_Dialog", "冷暖色调"))
        self.R.setText(_translate("Add_User_Dialog", "R"))
        self.G.setText(_translate("Add_User_Dialog", "G"))
        self.B.setText(_translate("Add_User_Dialog", "B"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rgb_customize), _translate("Add_User_Dialog", "自定义颜色"))


