# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_MainWindow4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui__MainWindow(object):
    def setupUi(self, UI_MainWindow):
        UI_MainWindow.setObjectName("UI_MainWindow")

        UI_MainWindow.resize(980, 780)
        UI_MainWindow.setMinimumSize(980, 780)
        UI_MainWindow.setMaximumSize(980, 780)
        self.gridLayout = QtWidgets.QGridLayout(UI_MainWindow)
        self.gridLayout.setObjectName("gridLayout")

        self.label_show_camera = QtWidgets.QLabel(UI_MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_show_camera.sizePolicy().hasHeightForWidth())
        self.label_show_camera.setSizePolicy(sizePolicy)
        self.label_show_camera.setMinimumSize(QtCore.QSize(500, 0))
        self.label_show_camera.setText("")
        self.label_show_camera.setObjectName("label_show_camera")
        self.gridLayout.addWidget(self.label_show_camera, 0, 1, 1, 1)

        self.label_show_id = QtWidgets.QLabel(UI_MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_show_id.sizePolicy().hasHeightForWidth())
        self.label_show_id.setSizePolicy(sizePolicy)

        font = QtGui.QFont()
        font.setPointSize(12)

        self.label_show_id.setFont(font)
        self.label_show_id.setText("")
        self.label_show_id.setObjectName("label_show_id")
        self.gridLayout.addWidget(self.label_show_id, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)

        self.__layout_fun_button = QtWidgets.QVBoxLayout()
        self.__layout_fun_button.setObjectName("__layout_fun_button")

        self.button_open_camera = QtWidgets.QPushButton(UI_MainWindow)
        self.button_open_camera.setFont(font)
        self.button_open_camera.setObjectName("button_open_camera")
        self.__layout_fun_button.addWidget(self.button_open_camera)

        self.button_select_user = QtWidgets.QPushButton(UI_MainWindow)
        self.button_select_user.setFont(font)
        self.button_select_user.setObjectName("button_select_user")
        self.__layout_fun_button.addWidget(self.button_select_user)

        self.button_add_user = QtWidgets.QPushButton(UI_MainWindow)
        self.button_add_user.setFont(font)
        self.button_add_user.setObjectName("button_add_user")
        self.__layout_fun_button.addWidget(self.button_add_user)

        self.button_update_user = QtWidgets.QPushButton(UI_MainWindow)
        self.button_update_user.setFont(font)
        self.button_update_user.setObjectName("button_update_user")
        self.__layout_fun_button.addWidget(self.button_update_user)

        self.button_delete_user = QtWidgets.QPushButton(UI_MainWindow)
        self.button_delete_user.setFont(font)
        self.button_delete_user.setObjectName("button_delete_user")
        self.__layout_fun_button.addWidget(self.button_delete_user)

        self.button_close = QtWidgets.QPushButton(UI_MainWindow)
        self.button_close.setFont(font)
        self.button_close.setObjectName("button_close")
        self.__layout_fun_button.addWidget(self.button_close)

        self.gridLayout.addLayout(self.__layout_fun_button, 0, 0, 2, 1)

        self.retranslateUi(UI_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(UI_MainWindow)

    def retranslateUi(self, UI_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        UI_MainWindow.setWindowTitle(_translate("UI_MainWindow", "Client"))
        self.button_open_camera.setText(_translate("UI_MainWindow", "打开摄像头"))
        self.button_select_user.setText(_translate("UI_MainWindow", "查看用户列表"))
        self.button_add_user.setText(_translate("UI_MainWindow", "添加用户"))
        self.button_update_user.setText(_translate("UI_MainWindow", "修改用户配置"))
        self.button_delete_user.setText(_translate("UI_MainWindow", "删除用户"))
        self.button_close.setText(_translate("UI_MainWindow", "退出窗口"))
