# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui__MainWindow2(object):
    def __init__(self):
        self.label_show_camera = None
        self.button_close = None
        self.__layout_fun_button = None
        self.__layout_main = None
        self.horizontalLayout_2 = None
        self.total_area = None
        self.button_open_camera = None

    def setupUi(self, UI):
        UI.setObjectName("UI_MainWindow")
        UI.resize(960, 680)
        # 总区域
        self.total_area = QtWidgets.QWidget(UI)
        self.total_area.setObjectName("total_area")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.total_area)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        # 整体布局
        self.__layout_main = QtWidgets.QHBoxLayout()
        self.__layout_main.setObjectName("__layout_main")

        # 按键布局
        self.__layout_fun_button = QtWidgets.QVBoxLayout()
        self.__layout_fun_button.setSpacing(4)
        self.__layout_fun_button.setObjectName("__layout_fun_button")

        # 打开摄像头按钮
        self.button_open_camera = QtWidgets.QPushButton(self.total_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_open_camera.sizePolicy().hasHeightForWidth())
        self.button_open_camera.setSizePolicy(sizePolicy)
        self.button_open_camera.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_open_camera.setFont(font)
        self.button_open_camera.setObjectName("button_open_camera")

        # 退出按钮
        self.button_close = QtWidgets.QPushButton(self.total_area)
        self.button_close.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_close.setFont(font)
        self.button_close.setObjectName("button_close")

        # 把按键加入到按键布局中
        self.__layout_fun_button.addWidget(self.button_open_camera, 0, QtCore.Qt.AlignHCenter)
        self.__layout_fun_button.addWidget(self.button_close, 0, QtCore.Qt.AlignHCenter)
        
        self.label_show_camera = QtWidgets.QLabel(self.total_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_show_camera.sizePolicy().hasHeightForWidth())
        self.label_show_camera.setSizePolicy(sizePolicy)
        self.label_show_camera.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_show_camera.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_show_camera.setObjectName("label_show_camera")
        
        # 把某些控件加入到总布局中
        self.__layout_main.addLayout(self.__layout_fun_button)
        self.__layout_main.addWidget(self.label_show_camera)
        self.horizontalLayout_2.addLayout(self.__layout_main)
        UI.setCentralWidget(self.total_area)

        self.reTranslateUi(UI)
        QtCore.QMetaObject.connectSlotsByName(UI)

    def reTranslateUi(self, UI):
        _translate = QtCore.QCoreApplication.translate
        UI.setWindowTitle(_translate("UI_MainWindow", "FSLSystem"))
        self.button_open_camera.setText(_translate("UI_MainWindow", "打开摄像头"))
        self.button_close.setText(_translate("UI_MainWindow", "退出窗口"))
