# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_MainWindow2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui__MainWindow(object):
    def setupUi(self, UI_MainWindow):
        UI_MainWindow.setObjectName("UI_MainWindow")
        UI_MainWindow.resize(598, 480)

        # 总区域
        self.horizontalLayout = QtWidgets.QHBoxLayout(UI_MainWindow)
        self.horizontalLayout.setObjectName("horizontalLayout")

        # 按键布局
        self.__layout_fun_button = QtWidgets.QVBoxLayout()
        self.__layout_fun_button.setObjectName("__layout_fun_button")

        # 打开摄像头按钮
        self.button_open_camera = QtWidgets.QPushButton(UI_MainWindow)
        self.button_open_camera.setObjectName("button_open_camera")

        # 退出按钮
        self.button_close = QtWidgets.QPushButton(UI_MainWindow)
        self.button_close.setObjectName("button_close")

        # 把按键加入到按键布局中
        self.__layout_fun_button.addWidget(self.button_open_camera)
        self.__layout_fun_button.addWidget(self.button_close)

        # 把某些控件加入到总布局中
        self.horizontalLayout.addLayout(self.__layout_fun_button)
        self.label_show_camera = QtWidgets.QLabel(UI_MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setHeightForWidth(self.label_show_camera.sizePolicy().hasHeightForWidth())
        self.label_show_camera.setSizePolicy(sizePolicy)
        self.label_show_camera.setObjectName("label_show_camera")
        self.horizontalLayout.addWidget(self.label_show_camera)

        self.reTranslateUi(UI_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(UI_MainWindow)

    def reTranslateUi(self, UI_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        UI_MainWindow.setWindowTitle(_translate("UI_MainWindow", "Form"))
        self.button_open_camera.setText(_translate("UI_MainWindow", "关闭摄像头"))
        self.button_close.setText(_translate("UI_MainWindow", "退出窗口"))
