# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_MainWindow3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui__MainWindow(object):
    def setupUi(self, UI_MainWindow):
        UI_MainWindow.setObjectName("UI_MainWindow")
        UI_MainWindow.resize(980, 780)

        # 栅格布局
        self.gridLayout = QtWidgets.QGridLayout(UI_MainWindow)
        self.gridLayout.setObjectName("gridLayout")

        # 视频流标签
        self.label_show_camera = QtWidgets.QLabel(UI_MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setHeightForWidth(self.label_show_camera.sizePolicy().hasHeightForWidth())
        self.label_show_camera.setSizePolicy(sizePolicy)
        self.label_show_camera.setMinimumSize(QtCore.QSize(500, 0))
        self.label_show_camera.setObjectName("label_show_camera")
        self.gridLayout.addWidget(self.label_show_camera, 0, 1, 1, 1)

        # 文本标签
        self.label_faceInfo = QtWidgets.QLabel(UI_MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_faceInfo.sizePolicy().hasHeightForWidth())
        self.label_faceInfo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_faceInfo.setFont(font)
        self.label_faceInfo.setObjectName("label_faceInfo")
        self.gridLayout.addWidget(self.label_faceInfo, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)

        # 按钮标签
        self.__layout_fun_button = QtWidgets.QVBoxLayout()
        self.__layout_fun_button.setObjectName("__layout_fun_button")
        self.button_open_camera = QtWidgets.QPushButton(UI_MainWindow)
        self.button_open_camera.setFont(font)
        self.button_open_camera.setObjectName("button_open_camera")
        self.__layout_fun_button.addWidget(self.button_open_camera)
        self.button_close = QtWidgets.QPushButton(UI_MainWindow)
        self.button_close.setObjectName("button_close")
        self.button_close.setFont(font)
        self.__layout_fun_button.addWidget(self.button_close)
        self.gridLayout.addLayout(self.__layout_fun_button, 0, 0, 2, 1)

        self.retranslateUi(UI_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(UI_MainWindow)

    def retranslateUi(self, UI_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        UI_MainWindow.setWindowTitle(_translate("UI_MainWindow", "Form"))
        self.button_open_camera.setText(_translate("UI_MainWindow", "打开摄像头"))
        self.button_close.setText(_translate("UI_MainWindow", "退出窗口"))
